baseURL = "https://blog.monsterxx03.com/"
Title = "Shining Moon"
publishDir="docs"
# for smart copyright line, leave this blank and check [params.copyright]
copyright = "monsterxx03"

theme = "pickles"

enableRobotsTXT = true # generate robots.txt

# Syntax Highlighting ( https://gohugo.io/content-management/syntax-highlighting/ )
pygmentsCodefences = true

# Language Configuration
defaultContentLanguage = "en"

[params.copyright]
prefix = ""
holder = "monsterxx03"
startYear = "2017"
suffix = ""

[params]
paginate = 10
subtitle = "百种弊病,皆从懒生"
email = "xyj.asmy@gmail.com"
github = "monsterxx03"
linkedin = ""
twitter = "monsterxx03"
ga_api_key = "UA-98667627-1"
disqus = "mx03"
author = "X"
avatar = "avatar.png"
bio = "Infrastructure Engineer@Glow"
contact = "mailto:xyj.asmy@gmail.com"

[taxonomies]
author = "authors"
category = "categories"
tag = "tags"
preserveTaxonomyNames = false

[permalinks]
page = "/:slug/"
posts = "/:year/:month/:day/:title/"

[[menu.main]]
name = "Blog"
url = "/"
weight = 1

[[menu.main]]
name = "About"
url = "/aboutme"
weight = 2

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 3
